config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   resources :groups do
       resources :tallies do
      end
   end

  get "dashboard", to: "members#dashboard", as:'member_dashboard'
  get "dashboard/account", to: "members#account", as: 'member_account'
  get 'landings/index'
  post 'membership', to: "landings#membership"
  post 'contactus', to: "landings#contactus"
  post 'reserve', to: "landings#reserve"

  resources :teams do
    post 'add_member', on: :member
    delete 'remove_member', on: :member
    put 'transfer_ownership', on: :member
    get 'all_members', on: :member

  end

  devise_for :members, controllers: {invitations: 'devise/invitations', registrations: "members/registrations", sessions: "members/sessions", passwords: "members/passwords"}, skip: [:sessions, :registrations]

  resources :games do
    resources :reviews
  end

    root 'landings#index'

    devise_scope :member do
      get    "login"   => "members/sessions#new",         as: :new_member_session
      post   "login"   => "members/sessions#create",      as: :member_session
      get "/signout",  to: "members/sessions#destroy",     as: :destroy_member_session
      put    "update_notification"  => "members#update_notification"

      get    "signup"  => "members/registrations#new",    as: :new_member_registration
      post   "signup"  => "members/registrations#create", as: :member_registration
      put    "signup"  => "members/registrations#update", as: :update_member_registration
      get    "account" => "members/registrations#edit",   as: :edit_member_registration
    end

end

app/models/tally.rb
class Tally < ActiveRecord::Base
	belongs_to :group
end

app/controllers/tallies_controller.rb
class TalliesController < ApplicationController
 before_action :set_tally, only: [:show, :edit, :update, :destroy]
 layout 'dashboard'
 before_action :set_group
  # GET /tallies
  # GET /tallies.json
  def index
    @tallies = Tally.all
    @boss = Tally.order("total DESC").first
  end

  # GET /tallies/1
  # GET /tallies/1.json
  def show
  end

  # GET /tallies/new
  def new
    @tally = Tally.new
  end

  # GET /tallies/1/edit
  def edit
  end

  # POST /tallies
  # POST /tallies.json
  def create
    @tally = Tally.new(tally_params)
    @tally.group_id = @group.id
    params[:total] = params[:body]

    respond_to do |format|
      if @tally.save
        format.html { redirect_to group_tallies_path, notice: 'Tally was successfully created.' }
        format.json { render :show, status: :created, location: @tally }
      else
        format.html { render :new }
        format.json { render json: @tally.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tallies/1
  # PATCH/PUT /tallies/1.json
  def update
    respond_to do |format|
      if @tally.update(tally_params)
        format.html { redirect_to group_tallies_path(group_id:@group.id), notice: 'Tally was successfully updated.' }
        format.json { render :show, status: :ok, location: @tally }
      else
        format.html { render :edit }
        format.json { render json: @tally.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tallies/1
  # DELETE /tallies/1.json
  def destroy
    @tally.destroy
    respond_to do |format|
      format.html { redirect_to group_tallies_url, notice: 'Tally was successfully destroyed.' }
      format.json { head :no_content }
    end
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tally
      @tally = Tally.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tally_params
      params.require(:tally).permit(:name, :head, :body, :total, :kills)
    end
    #  check if the company has permission to access the group
   def set_group
     @group = Group.last
    # $grou = @group.id
    # check if company has permission to view the group
    # if !(@group.company_id == @company.id)
    #   redirect_to company_path(@company.slug)
    # end
  end
end

app/helpers/tallies_helper.rb
module TalliesHelper
end

app/views/tallies/_form.html.erb
<div class col-sm-12 md-12 >
<%= form_for(@tally,url: group_tallies_path ) do |f| %>
  <% if @tally.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tally.errors.count, "error") %> prohibited this tally from being saved:</h2>

      <ul>
      <% @tally.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :head_shots %><br>
    <%= f.number_field :head %>
  </div>
  <div class="field">
    <%= f.label :body_shots %><br>
    <%= f.number_field :body %>
  </div>
    <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div
   <div class="field">
    <%= f.label :kills %><br>
    <%= f.text_field :kills %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/tallies/edit.html.erb
<div class="wrapper">

   <%= render 'teams/sidebar' %>
  
    <div class="main-panel expand">
        <!-- TODO Add Footer Partial -->
        <%= render partial: "members/navbar" %>


<div class="image-container set-full-height" >

  <br><br>



          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">


<div class="col-lg-12 col-md-12">

<%= render 'form' %>

 


</div>
<%= link_to 'Show', group_tally_path %>|
<%= link_to 'Back', group_tallies_path %>



            </div>
        </div><!-- end row -->



</div>

</div>
</div>

app/views/tallies/index.html.erb
<div class="wrapper">

   <%= render 'teams/sidebar' %>
  
    <div class="main-panel expand">
        <!-- TODO Add Footer Partial -->
        <%= render partial: "members/navbar" %>


<div class="image-container set-full-height" >

  <br><br>



          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">



<center><h3><%= @group.name.capitalize %> Tally Board</h3></center>

<div class="col-lg-12 col-md-12">
                        <div class="card box-shape">
                          <div class="header">
                          <% if current_member.present? && current_member.email == 'admin@bushfighterspaintballclub.com' %>
                            <%= link_to 'Add record', new_group_tally_path(group_id:@group.id), class: "btn float-right box-shape" %>
                            <%end%>
                          </div>

                    <div class="content">

                            <% if !flash[:notice].blank? %>
                              <div class="alert alert-info">
                              <%= flash[:notice] %>
                              </div>
                            <% end %>
                           <!--  <center>
                              <strong><h3><%= @group.name %></h3></strong>
                            </center> -->
                      <div>
                        <table  class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                  <th>Name</th>
                                  <th>Head Shots</th>
                                  <th>Body Shots</th>
                                  <th>Total</th>
                                  <th>Kills</th>
<% if current_member.present? && current_member.email == 'admin@bushfighterspaintballclub.com' %>
                                  <th colspan="2"></th>
                                  <%end%>
                                </tr>
                                <% @tallies.each do |tally| %>
                                  <tr>
                                    <td><%= tally.name %></td>
                                    <td><%= tally.head %></td>
                                    <td><%= tally.body %></td>
                                     <td><%= tally.total%></td> 
                                    <td><%= tally.kills %></td>
<% if current_member.present? && current_member.email == 'admin@bushfighterspaintballclub.com' %>
                                    <td><%= link_to 'Modify', edit_group_tally_path(id: tally.id) %></td>
                                    <td><%= link_to 'Delete', group_tally_path(id: tally.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                    <%end%>
                                  </tr>
                                <% end %>
                              </tbody>
                        </table>
                      </div>

                      </div>
                      </div>

<br>




            </div>
        </div><!-- end row -->



</div>

</div>
</div>

app/views/tallies/new.html.erb
<div class="wrapper">

   <%= render 'teams/sidebar' %>
  
    <div class="main-panel expand">
        <!-- TODO Add Footer Partial -->
        <%= render partial: "members/navbar" %>


<div class="image-container set-full-height" >

  <br><br>



          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">


<div class="col-lg-12 col-md-12">

<%= render 'form' %>

</div>
<%= link_to 'Back', group_tallies_path %>



            </div>
        </div><!-- end row -->



</div>

</div>
</div>

app/views/tallies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tally.name %>
</p>

<p>
  <strong>Head:</strong>
  <%= @tally.head %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tally.body %>
</p>

<p>
  <strong>Total:</strong>
  <%= @tally.total %>
</p>

<p>
  <strong>Kills:</strong>
  <%= @tally.kills %>
</p>