config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   resources :groups do
       resources :tallies do
      end
   end

  get "dashboard", to: "members#dashboard", as:'member_dashboard'
  get "dashboard/account", to: "members#account", as: 'member_account'
  get 'landings/index'
  post 'membership', to: "landings#membership"
  post 'contactus', to: "landings#contactus"
  post 'reserve', to: "landings#reserve"

  resources :teams do
    post 'add_member', on: :member
    delete 'remove_member', on: :member
    put 'transfer_ownership', on: :member
    get 'all_members', on: :member

  end

  devise_for :members, controllers: {invitations: 'devise/invitations', registrations: "members/registrations", sessions: "members/sessions", passwords: "members/passwords"}, skip: [:sessions, :registrations]

  resources :games do
    resources :reviews
  end

    root 'landings#index'

    devise_scope :member do
      get    "login"   => "members/sessions#new",         as: :new_member_session
      post   "login"   => "members/sessions#create",      as: :member_session
      get "/signout",  to: "members/sessions#destroy",     as: :destroy_member_session
      put    "update_notification"  => "members#update_notification"

      get    "signup"  => "members/registrations#new",    as: :new_member_registration
      post   "signup"  => "members/registrations#create", as: :member_registration
      put    "signup"  => "members/registrations#update", as: :update_member_registration
      get    "account" => "members/registrations#edit",   as: :edit_member_registration
    end

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "400x600#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :members
	has_many :reviews
	#include FriendlyId
	# searchkick
	extend FriendlyId
    friendly_id :name, use: :slugged
end

app/models/game_reservation.rb
class GameReservation < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many  :tallies, dependent: :destroy
end

app/models/joint_member_team.rb
class JointMemberTeam < ActiveRecord::Base
  belongs_to :member
  belongs_to :team
end

app/models/jointmemberteam.rb
class Jointmemberteam < ActiveRecord::Base
  belongs_to :member
  belongs_to :team
end

app/models/member.rb
class Member < ActiveRecord::Base

  has_many :games
  has_many :joint_member_teams
  has_many :reviews, dependent: :destroy
  has_many :teams, :through => :joint_member_teams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    # Try building a slug based on the following fields in
  	# increasing order of specificity.

end

app/models/membership.rb
class Membership < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :games
	belongs_to :members
end

app/models/tally.rb
class Tally < ActiveRecord::Base
	belongs_to :group
end

app/models/team.rb
class Team < ActiveRecord::Base
include FriendlyId

 has_many :joint_member_teams 
 has_many :members, :through => :joint_member_teams
 mount_uploader  :logo, LogoUploader
 mount_uploader  :banner, BannerUploader


    friendly_id :name, use: :slugged

    def should_generate_new_friendly_id?
    	 slug.nil? || name_changed? || new_record?
    end
    
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  layout 'dashboard'
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :set_member
  before_action :authenticate_member!, except: [:index, :show ]
  # before_action :set_review



  def index
    @games = Game.all
  end


  def show
    @reviews = Review.where(game_id:@game.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating)
    end
  

  end


  def new
    @game = Game.new
  end


  def edit
  end


  def create
    @game = Game.new(game_params)
    @game.member_id =  @member.id

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_game
      @game = Game.friendly.find(params[:id])
      
    end


    def game_params
      params.require(:game).permit(:title, :image, :description, :slug)
    end


    def set_member
        @member = current_member
    end

    # def set_review
    #   @review = Review.find(params[:id] || params[:review_id])
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tallies_helper.rb
module TalliesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_header.html.erb
		<!-- Search Navbar - START -->
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Paint Ball</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <% if member_signed_in? %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li class="divider"></li>
                </ul>
            </li>
            <li class="active"><%= link_to "New Game", new_game_path, class: "active"%></li>

            <li><%= link_to "Sign out", new_member_session_path, class: "active"%></li>
            
            <%else%>
            <li><%= link_to "Sign Up", new_member_registration_path, class: "active"%></li>
		   <li><%= link_to "Sign In", new_member_session_path, class: "active"%></li>
		<%end%>
        </ul>
        <div class="col-sm-3 col-md-3 pull-right">
            <form class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</nav>

<!-- Search Navbar - END -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BushFighters Paintball Clubs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title> Dashboard </title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
     
     <%= stylesheet_link_tag   'dashboard' %>

     <%= csrf_meta_tags %>

</head><!--/head-->

<body>

    <%= yield %>

 


<%= javascript_include_tag 'dashboard' %>
<script type="text/javascript">
        $(document).ready(function(){

            demo.initChartist();

            $.notify({
                icon: 'ti-gift',
                message: "Welcome to <b>Paper Dashboard</b> - a beautiful Bootstrap freebie for your next project."

            },{
                type: 'success',
                timer: 4000
            });

        });
    </script>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bushfighters Paintball Club</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

      <%= csrf_meta_tags %>
</head><!--/head-->

<body id="home" class="homepage">

    <%= yield %>

 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Paintball</title>
    <!--     Fonts and icons     -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

      <%= csrf_meta_tags %>
</head><!--/head-->

<body id="home" class="homepage">

    <%= yield %>

 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/layouts/wizard.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
  <link rel="icon" type="image/png" href="assets/img/favicon.png" />
  <title>Paintball</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Fonts and Icons -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'dashboard', 'wizard' %> 
  <%= javascript_include_tag 'dashboard', 'wizard' %>

</head>

<body>

   <%= yield %>
  

  

</body>

</html>