config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   resources :groups do
       resources :tallies do
      end
   end

  get "dashboard", to: "members#dashboard", as:'member_dashboard'
  get "dashboard/account", to: "members#account", as: 'member_account'
  get 'landings/index'
  post 'membership', to: "landings#membership"
  post 'contactus', to: "landings#contactus"
  post 'reserve', to: "landings#reserve"

  resources :teams do
    post 'add_member', on: :member
    delete 'remove_member', on: :member
    put 'transfer_ownership', on: :member
    get 'all_members', on: :member

  end

  devise_for :members, controllers: {invitations: 'devise/invitations', registrations: "members/registrations", sessions: "members/sessions", passwords: "members/passwords"}, skip: [:sessions, :registrations]

  resources :games do
    resources :reviews
  end

    root 'landings#index'

    devise_scope :member do
      get    "login"   => "members/sessions#new",         as: :new_member_session
      post   "login"   => "members/sessions#create",      as: :member_session
      get "/signout",  to: "members/sessions#destroy",     as: :destroy_member_session
      put    "update_notification"  => "members#update_notification"

      get    "signup"  => "members/registrations#new",    as: :new_member_registration
      post   "signup"  => "members/registrations#create", as: :member_registration
      put    "signup"  => "members/registrations#update", as: :update_member_registration
      get    "account" => "members/registrations#edit",   as: :edit_member_registration
    end

end

app/models/member.rb
class Member < ActiveRecord::Base

  has_many :games
  has_many :joint_member_teams
  has_many :reviews, dependent: :destroy
  has_many :teams, :through => :joint_member_teams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    # Try building a slug based on the following fields in
  	# increasing order of specificity.

end

app/controllers/members/confirmations_controller.rb
class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/invitations_controller.rb
# class Members::InvitationsController < Devise::InvitationsController
#   layout 'signin'
#    skip_filter :require_no_authentication, :only => :edit
#    before_action :devise_configure_permitted_parameters, if: :devise_controller?

#   protected




#   def devise_configure_permitted_parameters
#   	if member_signed_in?
#       sign_out current_member
#     end

#     devise_parameter_sanitizer.for(:accept_invitation) << :name
#   end
  

# end

app/controllers/members/passwords_controller.rb
class Members::PasswordsController < Devise::PasswordsController
  layout 'signin'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
layout 'signin'
# before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resourc
  def create
    super
  end


  # GET /resource/edit
  def edit
    @member = current_member
    # @notification = Notification.where(member_id: @member.id, read: 0)
    # render :layout => 'member_dashboard'
    # super

  end

  # PUT /resource
  def update
    @member = current_member
    # @notification = Notification.where(member_id: @member.id, read: 0)
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the member wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :name
  #   if Rails.env.production?
  #     notifier = Slack::Notifier.new "https://hooks.slack.com/services/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", channel: '#development', membername: 'signup'
  #     notifier.ping "New Signup by " + params[:member][:name] + " email: " + params[:member][:email]
  #   end
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :name
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   # member_dashboard_path
  #   redirect_to  new_team_path
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
layout 'signin'

  # GET /resource/sign_in
   # def new
   #   super
   # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

  def after_sign_in_path_for(resource)
      # member_dashboard_path
     member_dashboard_path
  end

end

app/controllers/members_controller.rb
require 'bcrypt'
class MembersController < ApplicationController
	layout 'dashboard'
	before_action :authenticate_member!

	# this is used to initial member's object to that it will be available to all 
	# method without recalling it again
	before_filter :set_up_member

    def set_up_member
        @member = current_member
    end






   def account
    if params[:update].present?
      bcrypt_object = BCrypt::Password.new(@member.encrypted_password)
      password_hash = ::BCrypt::Engine.hash_secret(params[:current_password], bcrypt_object.salt)
        if password_hash == @member.encrypted_password
          if !params[:password].blank?
            if (params[:password] == params[:confirm_password])
              @member.update_attributes(email: params[:email], name: params[:name], password: params[:password])
              flash.now[:success] = "Account Updated Successfully"
            else
              flash.now[:danger] = "Password Didn't match"
            end
          else
            @member.update_attributes(email: params[:email], name: params[:name])
             flash.now[:success] = "Account Updated Successfully"
          end
        else
          flash.now[:danger] = "Current password not correct"
        end
     end
  end


  def dashboard

  end







  def check_password
  	 bcrypt_object = BCrypt::Password.new(@member.encrypted_password) 
     password_hash = ::BCrypt::Engine.hash_secret(params[:current_password], bcrypt_object.salt)
	    if password_hash == @member.encrypted_password
	    	render plain: "correct"
	    else
	    	render plain: "wrong"
	    end
  end


    # parameters used to update the notification
  def update_notification_params
    params.permit(:read)
  end





end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_navbar.html.erb
<nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <% if @team.nil? %>
                       <%= image_tag('bh.jpg', style:"height: 90px;width: 720px;" )%>
                    <% end %>

                </div>
                <div class="collapse navbar-collapse">

                    <ul class="nav navbar-nav navbar-right">



                        <% if !@team.nil? %>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <p><%= @team.name %></p>
                                <i class="ti-settings"></i>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                   <%= link_to edit_team_path(params[:team_id ] || params[:id ] ) do %> Settings <% end %>
                                </li>
                            </ul>
                        </li>
                        <% end %>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- this should  dynamic give member name -->
                                 <p>Welcome!</p> 
                                 <i class="ti-user"></i>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                               <li><%= link_to "Dashboard", member_dashboard_path %></li>
                              <!--  <li> <%= link_to "Account", member_account_path %> </li>-->
                               <li><%= link_to "Sign Out", destroy_member_session_path, method: :delete %></li> 
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

app/views/members/_when_empty.html.erb
<div class="row">

    <div class="col-lg-12 col-md-12">
        <div>

        <div  class="row sharing-area text-center ">
            <br> <br> <br> <br>
            <% if current_member.present? && current_member.email == 'admin@bushfighterspaintballclub.com' %>
            <strong><h5 style="color:#FFFFFF">You don't have any  Team yet, create one now</h5></strong>
             <%= link_to new_team_path do %>
                <button  type="button" class="btn btn-raised btn-twitter">New Team</button>

               <br><br> <br>
            <% end %>
            <%else%>
            <strong><h5 style="color:#FFFFFF" >You don't have any  Team yet, contact admin to create your team</h5></strong>
            <%end%>
        </div>
        </div>
    </div>
</div>
    

app/views/members/account.html.erb
<div class="wrapper">
    <div class="main-panel expand">
       <!-- TODO Add Footer Partial -->
        <%= render partial: "navbar" %>
        <div class="content">
            <div class="container-fluid">
              <div class="row">

                <div class='col-md-8 col-md-offset-2'>
                    
                        <div class="card box-shape">
                            <div class="header">
                                <h4 class="title"> Account Details </h4>
                            </div>
                            <div class="content">
                             
                                <form id="form" method="post">
                                  <input type="hidden" name="update" value="update">
                                  <div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Name</label>
                                                <input type="text" class="form-control border-input"  placeholder="Firstname Lastname" name="name" value="<%= @user.name %>">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Email</label>
                                                <input type="email" class="form-control border-input" placeholder="Email Address" class="address" name="email" value="<%= @user.email %>">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label >Current Password</label>
                                                <input id="current-password" type="password" class="form-control border-input"  placeholder="Current password" name="current_password" >
                                            </div>
                                        </div>
                                    </div>

                                     <hr>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Password</label>
                                                <input type="password" class="form-control border-input" placeholder="Password" name="password">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Confirm Password</label>
                                                <input type="password" id="confirm-password" class="form-control border-input" placeholder="Confirm Password" name="confirm_password"  >
                                            </div>
                                        </div>
                                    </div>

                                   <!-- add csrf token -->
                                    <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 

                                    <div class="text-center">
                                        <button id="update"  class="btn btn-info btn-fill btn-wd">  Update </button>
                                    </div>                               
                                  </form>
                                
                                    
                               
                            </div>
                        </div>                       
                    </div>           
              </div>
            </div>
        </div>

    </div>
</div>

<script>

<% flash.each do |key, value| %>
    showMessage('top','center', "<%= value %>", <%= (key == "success") ? 2: 4 %>);                   
<% end %>

$("#update").click(function(event){
  var confirmed = true;
  var currentPassword = $("#current-password").val();
   if (!currentPassword){
     showMessage('top','center', "Current Password cannot be empty", 4); 
     event.preventDefault();
  } else {
    $.ajax({
          url: '<%= check_password_path %>', 
          type: 'GET',
          data: {current_password: currentPassword },
          success: function(data){
              $("#form").submit();
          },
          error : function(jqXHR, textStatus, errorThrown) {
               
           }
       });
  }
 
});







</script>

app/views/members/dashboard.html.erb
<div class="wrapper">
<%= render 'teams/sidebar' %>
<div class="main-panel expand">
<%= render partial: "members/navbar" %>
<div class="content">
<div class="container-fluid">
<!-- <div class="row">
	<div class="col-sm-6">Teams</div>
	<div class="col-sm-6">Games</div>
</div>
 --><div class="row">

                        <div class="header col-md-4 col-md-offset-2">
                                 <strong><h4 style="color:#FFFFFF" class="title">Teams (<%= @member.teams.length %>)</h4></strong>
                        </div>
                        <% if current_member.present? && current_member.email == 'admin@bushfighterspaintballclub.com' %>
                        <% if @member.teams.length > 0 %>
                          <div class="col-md-4 col-md-offset-2">
                              <%= link_to new_team_path do %>
                                  <button style="color:#FFFFFF"  type="button" class="btn btn-raised btn-twitter">New Team</button>
                              <% end %>
                              <% end %>
                          </div>


                        <% end %>
                        <!-- test for zero state -->
                        <% if @member.teams.length > 0 %>

                          <div class="card col-md-8 col-md-offset-2 box-shape">
                            <div class="content">
                                <ul class="list-unstyled team-members">

                                    <% @member.joint_member_teams.each do | member_team| %>
                                      <li>


                                        <%= link_to  member_dashboard_path do%>  
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <div class="">
                                                    <% if member_team.team.logo.file.nil? %>  
                                                           <%= image_tag('logo.png', height:"55") %>
                                                       <% else %>

                                                            <img src="<%= member_team.team.logo.url %>" height="55"  />
                                                       <% end %>
                                                </div>
                                            </div>
                                            <div class="col-xs-6">
                                                <%= member_team.team.name %>
                                                <!-- get number of collaborators -->
                                                <% num_members = member_team.team.members.length  %>

                                                <br>
                                                <% if member_team.status == 0 %>
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                             <span class="text-muted">
                                                               Status: Owner
                                                             </span>
                                                        </div>
                                                        <div class="col-md-6">
                                                          <span class="text-muted">
                                                            No of member(s): <%= num_members %>
                                                          </span>
                                                        </div>
                                                    </div>
                                                <% elsif member_team.status == 1 %>
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                             <span class="text-muted">
                                                               Status:  Admin
                                                             </span>
                                                        </div>
                                                        <div class="col-md-6">
                                                          <span class="text-muted">
                                                            No of member(s): <%= num_members %>
                                                          </span> 
                                                        </div>
                                                    </div>
                                                <% elsif member_team.status == 2 %>
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                             <span class="text-muted">
                                                               Status: User 
                                                             </span> 
                                                        </div>
                                                        <div class="col-md-6">
                                                          <span class="text-muted">
                                                            No of member(s): <%= num_members %>
                                                          </span> 
                                                        </div>
                                                    </div>
                                                <% elsif %>

                                                <% end %>

                                            </div>

                                            <div class="col-xs-3 text-right">
                                               <!--  <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-envelope"></i></btn> -->
                                            </div>
                                        </div>

                                        <% end %>
                                    </li>
                                  <% end %>
                                </ul>
                            </div>
                        </div>


                        <% else %>
                          <div class="col-md-8 col-md-offset-2">
                            <div class="content">
                              <%= render partial: "when_empty" %>
                            </div>
                          </div>
                        <% end %>

                    </div>


</div>
</div>
</div>
</div>